FROM node:18.18.2-alpine3.18 as build

# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn apt-key add - && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install --no-install-recommends yarn

# make folder 'app' the default working directory
WORKDIR /app

# files copied from the source directory to the current working directory
COPY /source/ .

# install project dependencies
# export PATH="$(yarn global bin):$PATH"
RUN yarn global add @quasar/cli@1.1.0
RUN yarn install

# build the application
RUN quasar build

FROM nginx:1.21.3-alpine

# copy the build output to the default Nginx public folder
COPY --from=build /app/dist/spa /usr/share/nginx/html

# expose port 80
EXPOSE 80
