name: aws_cloud_forge
services:
  website:
    build:
      context: C:\Users\Bispo\WorkSpace\k8s.dev.br\website
      dockerfile: Dockerfile.dev
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: ./source
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: ./docker-entrypoint.sh
        target: /entrypoint.sh
        bind:
          create_host_path: true

